# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master
  - feature/*

pool: 'Default'

steps:
  - task: SonarQubePrepare@4
    inputs:
      SonarQube: 'SQ_BP'
      scannerMode: 'Other'
      extraProperties: '| sonar.projectKey=MonoRepo.Module1 sonar.projectName=MonoRepo.Module1'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      sonarQubeRunAnalysis: true
      sqMavenPluginVersionChoice: 'latest'

  - task: SonarQubePublish@4
    inputs:
      pollingTimeoutSec: '300'
